# Generated by Django 3.1.3 on 2020-12-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0002_auto_20201126_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Student Name', max_length=100)),
                ('email', models.CharField(help_text='Student Name', max_length=100)),
                ('contact', models.CharField(help_text='Student Name', max_length=100)),
                ('address', models.CharField(help_text='Student Name', max_length=250)),
                ('dob', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
