# Generated by Django 3.1.3 on 2020-12-02 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('promo', '0004_auto_20201201_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='promo.student'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(verbose_name='Date of birth'),
        ),
    ]
