# Generated by Django 3.1.3 on 2020-12-04 12:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_male'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bio',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
